language: python
python:
 - "2.6"
 - "2.7"
env:
 - FLASK_VERSION=0.8 DROPBOX_VERSION=1.4
 - FLASK_VERSION=0.9 DROPBOX_VERSION=1.4
 - FLASK_VERSION=0.8 DROPBOX_VERSION=1.4.1
 - FLASK_VERSION=0.9 DROPBOX_VERSION=1.4.1
 - FLASK_VERSION=0.8 DROPBOX_VERSION=1.5
 - FLASK_VERSION=0.9 DROPBOX_VERSION=1.5
 - FLASK_VERSION=0.8 DROPBOX_VERSION=1.5.1
 - FLASK_VERSION=0.9 DROPBOX_VERSION=1.5.1
install:
 - "pip install -r testapp/requirements.txt --use-mirrors"
 - "pip install -I Flask==$FLASK_VERSION"
 - "pip install -I https://www.dropbox.com/static/developers/dropbox-python-sdk-$DROPBOX_VERSION.zip"
 - "pip install -e ."
before_script: "python testapp/manage.py settings_local"
script: "unit2 discover -s testapp/"
